#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("mobileClient.Droid.Resource", IsApplication=true)]

namespace mobileClient.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010002
			public const int colorAccent = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorPrimaryDark = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int launcher_background = 2130771973;
			
			// aapt resource value: 0x7F010000
			public const int ListViewHighlighted = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ListViewSelected = 2130771969;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int begaet = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int calculator_logo = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int icon_about = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int icon_body = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int icon_feed = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int icon_gantel = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int icon_home = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int icon_user = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int kachaetsa = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int launch_screen = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int mainIcon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int xamarin_logo = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int Launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MainTheme = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MyDatePickerDialogTheme = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int MyDatePickerStyle = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int MyTheme = 2130968580;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
